apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-calls
  labels:
    app: infinite-calls
spec:
  replicas: 10
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      name: infinite-calls
      labels:
        component: web
spec:
      containers:
      - name: infinite-calls
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://20.62.27.248; done"


